# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
description = "A Cloud Native Buildpack that contributes the Contrast Security Agent and configures it to connect to the service"
homepage = "https://github.com/jharper-sec/contrast-security"
id = "jharper-sec/contrast-security"
keywords = [
  "contrast-security",
  "agent",
  "security",
  "java",
  "application-security",
]
name = "Paketo Buildpack for Contrast Security"
sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
version = "0.0.1"

[[buildpack.licenses]]
type = "Apache-2.0"
uri = "https://github.com/jharper-sec/contrast-security/blob/main/LICENSE"

[metadata]
include-files = [
  "LICENSE",
  "README.md",
  "linux/amd64/bin/build",
  "linux/amd64/bin/detect",
  "linux/amd64/bin/main",
  "linux/amd64/bin/helper",
  "linux/arm64/bin/build",
  "linux/arm64/bin/detect",
  "linux/arm64/bin/main",
  "linux/arm64/bin/helper",
  "buildpack.toml",
  "resources/contrast_security.yaml",
]
pre-package = "scripts/build.sh"

[[metadata.dependencies]]
cpes = ["cpe:2.3:a:contrastsecurity:contrast-agent:6.12.1:*:*:*:*:*:*:*"]
id = "contrast-java"
name = "Contrast Security Java Agent"
purl = "pkg:generic/contrast-agent@6.12.1"
sha256 = "72a75fbae8959382e856697b1980b7173fc06ac55935e6983dfb90730bd5bb55"
stacks = ["*"]
uri = "https://repo1.maven.org/maven2/com/contrastsecurity/contrast-agent/6.12.1/contrast-agent-6.12.1.jar"
version = "6.12.1"

[[metadata.dependencies.licenses]]
type = "Proprietary"
uri = "https://www.contrastsecurity.com/enduser-terms-0317a"

[[stacks]]
id = "*"

[[targets]]
arch = "amd64"
os = "linux"

[[targets]]
arch = "arm64"
os = "linux"
